# Generated by Django 2.2.7 on 2019-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AticalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, verbose_name='name')),
                ('image_body', models.ImageField(blank=True, null=True, upload_to='blog_image', verbose_name='图片')),
            ],
        ),
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=models.TextField(verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=225, verbose_name='标题'),
        ),
    ]
