# Generated by Django 2.2.7 on 2019-12-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191203_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aticalimage',
            name='image_body',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image/', verbose_name='图片'),
        ),
    ]
