# Generated by Django 2.0 on 2020-02-15 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200214_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artical',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='artical',
            name='pushed',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 9, 28, 46, 500386), verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
