# Generated by Django 2.2.10 on 2020-05-02 16:15

import DjangoUeditor.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200215_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
        migrations.CreateModel(
            name='ActicalTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_content', models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/jhw/code/django-demo/media'), upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('artical', models.ManyToManyField(to='blog.Artical')),
            ],
        ),
    ]
