# Generated by Django 2.2.10 on 2020-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200502_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签id')),
                ('tag_content', models.CharField(max_length=64, verbose_name='标签内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('artical', models.ManyToManyField(to='blog.Artical')),
            ],
        ),
        migrations.RenameModel(
            old_name='ActicalImage',
            new_name='ArticalImage',
        ),
        migrations.DeleteModel(
            name='ActicalTag',
        ),
    ]
