# Generated by Django 2.2.10 on 2020-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200502_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articaltag',
            name='artical',
        ),
        migrations.AddField(
            model_name='artical',
            name='articaltag',
            field=models.ManyToManyField(to='blog.ArticalTag'),
        ),
        migrations.AlterModelTable(
            name='artical',
            table='blog_artical',
        ),
        migrations.AlterModelTable(
            name='articaltag',
            table='blog_articaltag',
        ),
    ]
